module.exports = {
    mode: 'jit',
    purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {},
    },
    variants: {
        extend: {},
    },
    plugins: [],
    /*corePlugins: [
        'flex',
        'margin',
        'padding',
        'display',
        'clear',
        'position',
        'visibility',
        'zIndex',
        'flexDirection',
        'flexWrap',
        'flexGrow',
        'flexShrink',
        'gridTemplateColumns',
        'gridColumn',
        'gridColumnStart',
        'gridColumnEnd',
        'gridTemplateRows',
        'gridRow',
        'gridRowStart',
        'gridRowEnd',
        'gap',
        'justifyContent',
        'justifyItems',
        'alignItems',
        'alignContent',
        'fontSize',
        'fontStyle',
        'fontWeight',
        'lineHeight',
        'textAlign',
        'textColor',
        'textOpacity',
        'textDecoration',
        'textTransform',
        'textOverflow',
        'whitespace',
        'wordBreak',
        'opacity',
        'cursor',
        'userSelect',
        'outline',
        'width',
        'height',
        'overflow'
    ]*/
}