"""
Django settings for bkz3 project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import os
from .local_settings import *
from django.utils.translation import gettext_lazy as _
from datetime import timedelta
import json

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'jquery',
    'djangoformsetjs',
    'drf_recaptcha',
    'report_builder',
    'mptt',
    'axes',
    'django_crontab',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'haystack',
    'ckeditor',
    'django_q',
    'nested_inline',
    'django_middleware_global_request',
    'prettyjson',
    'widget_tweaks',
    # local
    'elastic_commands',
    'common',
    'app_info',
    'users',
    'gallery',
    'change_history',
    'contractor_invites',
    'contractor_docs',
    'crm',
    'common.catalogs',
    'common.accounting_catalogs',
    'common.estimates',
    'contractor_permissions',
    'contractor_reports',
    'tags',
    'staff',
    'notes',
    'bpms.meetings',
    'bpms.workgroups',
    'bpms.bpms_common',
    'bpms.comments',
    'bpms.tasks',
    'bpms.widgets',
    'test_currentprofile',
    'bpms.chat',
    'bpms.chat_ai',
    'bpms.processes',
    'bpms.news',
    'bpms.event_calendar',
    'bpms.workload',
    'bpms.favorites',
    'bpms.personal_planes',
    'bpms.retrospective',
    'bpms.okr',
    'bpms.reactions',
    'bpms.day_summary',
    'bpp',
    'notifications',
    'custom_permission',
    'integration_1c',
    'corsheaders',
    'flowchart',
    'content_item_gos24',
    'pvh',
    'user_work_status',
    'static_pages',
    'bpms.voting',
    'tickets',
    'consolidation',
    'wiki',
    'risk_assessment',
    'invest_projects_info',
    'billing',
    'accounting_reports',
    'ehub',
    'sports_facilities_info',
    'help_desk.apps.HelpDeskConfig',
    'reports',
    'analytics',
    'demo',
    'django_cryptography',
    'django_elasticsearch_dsl',
    'es_search.apps.EsSearchConfig',
    'sla',
    'tg_mini_app',
    'catalog_info',
    'contractor_access_tokens',
    'customer_contracts',
]

AUTH_USER_MODEL = 'users.CustomUser'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'middleware.query_time.QueryTimeMiddleware',
    'middleware.request_timing.RequestTimingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.current_profile.middleware.ThreadLocalUserMiddleware',
    'contractor_permissions.middleware.ContractorPermissionMiddleware',
    'axes.middleware.AxesMiddleware',
    'django_middleware_global_request.middleware.GlobalRequestMiddleware',
]

if DEBUG is True:
    MIDDLEWARE.append('querycount.middleware.QueryCountMiddleware')

ROOT_URLCONF = 'bkz3.urls'
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]


def axes_get_username(request, credentials):
    """
    Извлекает логин для django-axes.
    Основной кейс — DRF JSON-логин с полем `email`.
    """
    # 1) DRF: request.data (твой кейс /api/v1/users/login/)
    request_data = getattr(request, "data", None)
    if request_data:
        username = request_data.get("email") or request_data.get("username")
        if username:
            return str(username).lower()

    # 2) credentials от backend'а (authenticate)
    if credentials:
        username = credentials.get("email") or credentials.get("username")
        if username:
            return str(username).lower()

    # 3) Обычная форма (админка и т.п.)
    post_data = getattr(request, "POST", None)
    if post_data:
        username = post_data.get("email") or post_data.get("username")
        if username:
            return str(username).lower()

    return None


AXES_ENABLED = True
AXES_META_PRECEDENCE_ORDER = [
    'HTTP_X_FORWARDED_FOR',
    'REMOTE_ADDR',
]
AXES_BEHIND_REVERSE_PROXY = True
AXES_LOCKOUT_CALLABLE = "users.views.lockout"
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25
AXES_ONLY_USER_FAILURES = False
AXES_LOCK_OUT_BY_USER_OR_IP = False
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_USERNAME_CALLABLE = 'bkz3.settings.axes_get_username'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bkz3.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru'

LANGUAGES = (
    ("ru", _("Russian")),
    ("kk", _("Kazakh")),
    ("en", _("English")),
)
MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_FALLBACK_LANGUAGES = {
    'default': ('ru', 'kk', 'en'),
    'ru': ('kk', 'en'),
    'kk': ('ru', 'en'),
    'en': ('ru', 'kk'),
}
LOCALE_PATHS = [BASE_DIR + '/locale']

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ONLYOFFICE_DOCUMENT_SERVER_PUBLIC_URL = (
    globals().get("ONLYOFFICE_DOCUMENT_SERVER_PUBLIC_URL")
    or os.getenv("ONLYOFFICE_DOCUMENT_SERVER_PUBLIC_URL", "")
).rstrip("/")
ONLYOFFICE_STORAGE_PUBLIC_URL = (
    globals().get("ONLYOFFICE_STORAGE_PUBLIC_URL")
    or os.getenv("ONLYOFFICE_STORAGE_PUBLIC_URL", BACKEND_URL)
).rstrip("/")
ONLYOFFICE_JWT_SECRET = (
    globals().get("ONLYOFFICE_JWT_SECRET")
    or os.getenv("ONLYOFFICE_JWT_SECRET", "")
)
ONLYOFFICE_DOWNLOAD_TOKEN_TTL = int(
    globals().get("ONLYOFFICE_DOWNLOAD_TOKEN_TTL")
    or os.getenv("ONLYOFFICE_DOWNLOAD_TOKEN_TTL", 900)
)
ONLYOFFICE_CALLBACK_TOKEN_TTL = int(
    globals().get("ONLYOFFICE_CALLBACK_TOKEN_TTL")
    or os.getenv("ONLYOFFICE_CALLBACK_TOKEN_TTL", 86400)
)
VOICE_INPUT_RECOGNIZE_URL = (
    globals().get("VOICE_INPUT_RECOGNIZE_URL")
    or os.getenv("VOICE_INPUT_RECOGNIZE_URL", "http://127.0.0.1:5080/recognize")
).rstrip("/")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DOCUMENT_LOCK_TIMEOUT = 7200

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'common.handlers.base_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'common.renderers.NoFormBrowsableAPIRenderer',
    ]
    # 'DEFAULT_RENDERER_CLASSES': [
    #     'rest_framework.renderers.JSONRenderer',
    # ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(weeks=26),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}
try:
    SIMPLE_JWT['ACCESS_TOKEN_LIFETIME'] = ACCESS_TOKEN_LIFETIME
except NameError:
    pass

if DEBUG is False:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = ['rest_framework.renderers.JSONRenderer', ]

from django.db import models

CUSTOM_PROTECT = models.PROTECT
CUSTOM_CASCADE = models.CASCADE
CUSTOM_SET_NULL = models.SET_NULL
CUSTOM_SET_DEFAULT = models.SET_DEFAULT
CUSTOM_DO_NOTHING = models.DO_NOTHING

CRONJOBS = [
    # ('*/2 * * * *', 'integration_1c.cron.get_remnants_from_1c_cron'),
    # ('*/2 * * * *', 'integration_1c.cron.check_order_find_order_form'),
    # ('*/2 * * * *', 'integration_1c.cron.check_order_find_pay_file'),
]

try:
    from .local_settings import LOCAL_REMNANT_CONTROL

    REMNANT_CONTROL = LOCAL_REMNANT_CONTROL
except ImportError:
    REMNANT_CONTROL = False
try:
    from .local_settings import MY_REMNANT_CONTROL
except ImportError:
    MY_REMNANT_CONTROL = False

HTTP_REFERER = False
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_REPLACE_HTTPS_REFERER = True
AVATAR_ROOT = f"{MEDIA_ROOT}/avatars/"
RECORDS_ROOT = f"{MEDIA_ROOT}/records/"
REPORT_TEMPLATES_ROOT = f"{MEDIA_ROOT}/report_templates/"

#: EMAIL службы поддержки(хелпдеск)
try:
    from .local_settings import SUPPORT_EMAIL
except ImportError:
    SUPPORT_EMAIL = 'HelpDesk@prst.ru'

#: Название компании (для текстов писем, и т.д)
try:
    from .local_settings import COMPANY_NAME
except ImportError:
    COMPANY_NAME = 'ООО "Промситех"'

#: Настройки заказа
try:
    from .local_settings import ORDER_DELIVERY
except ImportError:
    # ORDER_DELIVERY: 'address', 'point'
    ORDER_DELIVERY = 'address'

#: Короткое описание
try:
    from .local_settings import SHORT_COMPANY_NAME
except ImportError:
    SHORT_COMPANY_NAME = 'Промситех'

try:
    from .local_settings import GOODS_PRICE_BY_CATALOG
except ImportError:
    GOODS_PRICE_BY_CATALOG = True
try:
    from .local_settings import DEFAULT_PRICE_CURRENCY
except:
    DEFAULT_PRICE_CURRENCY = 'руб'
try:
    from .local_settings import DEFAULT_PRICE_TYPE_CODE
except ImportError:
    DEFAULT_PRICE_TYPE_CODE = None

try:
    from .local_settings import ZIP_FILE_SUFFIX
except ImportError:
    ZIP_FILE_SUFFIX = 'zipfiles'

ZIPFILES_ROOT = os.path.join(MEDIA_ROOT, ZIP_FILE_SUFFIX)

ZIPFILES_EXPIRE = 3600

try:
    from .local_settings import TASK_DATES_CONTROL
except ImportError:
    TASK_DATES_CONTROL = False

try:
    from .local_settings import FILTER_REMNANTS_BY_CUSTOM_STORAGES
except ImportError:
    FILTER_REMNANTS_BY_CUSTOM_STORAGES = False
try:
    from .local_settings import BITRIX_TOKEN
except ImportError:
    BITRIX_TOKEN = 'ПОЛУЧАЕМ ИЗ ВНЕШНЕЙ СИСТЕМЫ'

try:
    from .local_settings import BITRIX_OUTER_TOKEN
except ImportError:
    BITRIX_OUTER_TOKEN = 'НАЗНАЧАЕМ ВО ВНЕШНЕЙ СИСТЕМЕ'

try:
    from .local_settings import MOBILE_APP_GLOBAL_FRONT_SETTINGS
except ImportError:
    MOBILE_APP_GLOBAL_FRONT_SETTINGS = {
        "injectModules": {
            "notifications": True,
        },
        "injectComponents": [
            "TaskDetail",
        ],
    }

try:
    from .local_settings import MOBILE_APP_PRIVATE_OFFICE
except ImportError:
    MOBILE_APP_PRIVATE_OFFICE = (
        {
            "icon": "fi-rr-id-badge",
            "name": "Персональная информация",
            "path": "personal",
            "widget": "Personal",
        }
    )
try:
    from .local_settings import ORDER_WITHOUT_1C
except ImportError:
    ORDER_WITHOUT_1C = False

try:
    from .local_settings import GET_PROJECTS_AND_GROUPS_FROM_OTHER_BASE
except ImportError:
    GET_PROJECTS_AND_GROUPS_FROM_OTHER_BASE = False

try:
    from .local_settings import TOKEN_FOR_IMPORT_PROJECTS
except ImportError:
    TOKEN_FOR_IMPORT_PROJECTS = 'SOME_SECRET_TOKEN'
try:
    from .local_settings import GROUP_LABEL_IN_MENU  # Для переименования в промситехе
except ImportError:
    GROUP_LABEL_IN_MENU = 'Команды'

# Текст оферты по умолчанию
DEFAULT_OFFER_TEXT = 'Текст оферты'

# Вкл/выкл рассылки диллерам о выходе новостей на "Рабочем столе"
# письма отправляются в момент публикации новости
try:
    from .local_settings import DEALERS_EMAIL_NEWS_NOTIFICATION
except ImportError:
    DEALERS_EMAIL_NEWS_NOTIFICATION = False
try:
    from .local_settings import DIRECT_ORDER_FILES
except ImportError:
    DIRECT_ORDER_FILES = False

try:
    from .local_settings import MOBILE_FRONT_CATEGORIES
except ImportError:
    MOBILE_FRONT_CATEGORIES = {
                                  'dashboard': {'show_footer_menu': True},
                                  'tasks': {'show_footer_menu': True},
                                  'sprints': {'show_footer_menu': True},
                                  'chat': {'show_footer_menu': True},
                                  'meetings': {'show_footer_menu': False},
                                  'groups': {'show_footer_menu': False},
                                  'projects': {'show_footer_menu': False},
                                  'goods': {'show_footer_menu': True},
                                  'orders': {'show_footer_menu': True},
                                  'logistic': {'show_footer_menu': True},
                                  'contractors': {'show_footer_menu': False}
    }
try:
    from .local_settings import FILTER_BY_ORGANIZATIONS
except ImportError:
    FILTER_BY_ORGANIZATIONS = False

try:
    from .local_settings import INITIAL_ORGANIZATION
except ImportError:
    INITIAL_ORGANIZATION = None


try:
    from .local_settings import SMS_API
except ImportError:
    SMS_API = {
        "host": "",
        "key": "",
        "backend": "notifications.sms_backends.MobizonSMSBackend"
    }
try:
    from .local_settings import DRF_RECAPTCHA_SECRET_KEY
except ImportError:
    DRF_RECAPTCHA_SECRET_KEY = ""
    DRF_RECAPTCHA_TESTING = True

try:
    from .local_settings import TEMPDB_TABLESPACE
except ImportError:
    TEMPDB_TABLESPACE = ''




CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'extraPlugins': [
            'autolink',
            'clipboard',
            'embed',
            'image',
            'table',
            'tableresize',
            'tabletools',
            'uploadimage',
        ],
        'removePlugins': [
            'scayt',
            'forms',
            'language',
        ],
        'width': '100%',
        'height': '500px',
    },
    'description': {
        'toolbar': 'full',
        'extraPlugins': [
            'autolink',
            'clipboard',
            'embed',
            'image',
            'table',
            'tableresize',
            'tabletools',
            'uploadimage',
        ],
        'removePlugins': [
            'scayt',
            'forms',
            'language',
        ],
        'width': '100%',
        'height': '200px',
    }
}
try:
    from .local_settings import URLS
except ImportError:
    URLS = {
        'frontend_url': FRONTEND_URL,
        'backend_url': BACKEND_URL,
        'tasks': f"{FRONTEND_URL}/tasks",
        'meetings': f"{FRONTEND_URL}/meetings",
        'groups': f"{FRONTEND_URL}/groups",
        'projects': f"{FRONTEND_URL}/projects",
        'business_processes': f"{FRONTEND_URL}/BusinessProcesses",
        'chat': f"{FRONTEND_URL}/chat",
        'notifications': f"{FRONTEND_URL}",
        'dashboard': f"{FRONTEND_URL}/dashboard",
        'orders': f"{FRONTEND_URL}/orders",
        'my_bases': f"{FRONTEND_URL}/my-bases",
        'team': f"{FRONTEND_URL}/organization",
        'consolidation': f"{FRONTEND_URL}/consolidation",
        'moderation': f"{FRONTEND_URL}/moderation",
        'helpdesk_tickets': f"{FRONTEND_URL}/helpdesk/tickets/",
        'helpdesk_clients': f"{FRONTEND_URL}/directories/clients/",  # согласовать с фронтом
        'request_approvals': f"{FRONTEND_URL}/request-approvals",
    }

try:
    from .local_settings import INVITE_REGISTER_ONLY
except ImportError:
    INVITE_REGISTER_ONLY = False

try:
    from .local_settings import PDF_PARSER_URL
except ImportError:
    PDF_PARSER_URL = ''

try:
    from .local_settings import EHUB_TOKEN
except ImportError:
    EHUB_TOKEN = ''

try:
    from .local_settings import DID_SALT
except ImportError:
    DID_SALT = 'SET_ME_VALUE_AS_IN_DID'

try:
    from .local_settings import USE_ACCESS_GROUPS
except ImportError:
    USE_ACCESS_GROUPS = False

try:
    from .local_settings import DEFAULT_DSL_NAMESPACE
except ImportError:
    DEFAULT_DSL_NAMESPACE = 'connect'

try:
    from .local_settings import TG_MINI_APP_URL
except ImportError:
    TG_MINI_APP_URL = ''

REPORTS_UNIVERSAL_MODELS = [
'catalogs.ContractorModel',
'catalogs.ContractorDepartmentModel',
'catalogs.ContractorProfileModel',

'common.BaseModel',
'common.File',
'common.FileType',
'common.FolderModel',
'common.MimeType',

'chat.ChatModel',

'customer_contracts.CustomerContractModel',
'customer_contracts.CustomerContractProjectModel',
'customer_contracts.CustomerContractServicedCardModel',
'customer_contracts.CustomerContractStatusModel',

'estimates.AccumulationRegister',
'estimates.RegistrarDataSourceModel',
'estimates.RegistrarSectionModel',

'help_desk.HelpDeskTicketModel',
'help_desk.CustomerCardModel',
'help_desk.ContactPersonModel',
'help_desk.CustomerSupportSpecialistModel',
'help_desk.HelpDeskTicketTypeModel',
'help_desk.HelpDeskChannelModel',
'help_desk.HelpDeskTicketTypeModel',
'help_desk.HelpDeskTicketPriorityModel',
'help_desk.HelpDeskTicketStatusModel',
'help_desk.HelpDeskTicketTypeModel',
'help_desk.HelpDeskTicketCategoryModel',
'help_desk.CustomerCardStatusModel',
'help_desk.HelpDeskWorkLogModel',
'help_desk.CustomerCardAdminModel',

'meetings.PlannedMeetingModel',
'meetings.MeetingSectionModel',

'okr.InitiativesModel',
'okr.InitiativesRelatedObjectType',
'okr.KeyResultMetricsModel',
'okr.KeyResultsModel',
'okr.MissionModel',
'okr.NotificationFrequencyModel',
'okr.ObjectiveStatusModel',
'okr.ObjectiveVisor',
'okr.ObjectivesModel',
'okr.ValueEffortsModel',

'personal_planes.PersonalPlaneItemModel',
'personal_planes.PersonalPlaneModel',
'personal_planes.PersonalPlaneStatusModel',

'processes.WorkflowRequestModel',
'processes.WorkflowRequestTypeModel',
'processes.WorkflowRequestStatusModel',

'tags.TagModel',

'tasks.CostItemTaskModel',
'tasks.FastNumerator',
'tasks.HistoryOperator',
'tasks.LeadSourceModel',
'tasks.RejectionReasonModel',
'tasks.SprintProjectThroughModel',
'tasks.TaskBudgetModel',
'tasks.TaskCooperator',
'tasks.TaskCounterModel',
'tasks.TaskDeliveryModel',
'tasks.TaskDeliveryPointModel',
'tasks.TaskDifficulty',
'tasks.TaskDifficultyCriterion',
'tasks.TaskExecutionTimeModel',
'tasks.TaskLoadingGoodsModel',
'tasks.TaskModel',
'tasks.TaskOverdue',
'tasks.TaskPointModel',
'tasks.TaskPrerequisite',
'tasks.TaskRating',
'tasks.TaskScenarioModel',
'tasks.TaskSprintMember',
'tasks.TaskSprintModel',
'tasks.TaskStatusModel',
'tasks.TaskStatusTypeDependsModel',
'tasks.TaskStatusTypeModel',
'tasks.TaskStatusWorkTypeConnectModel',
'tasks.TaskTypeModel',
'tasks.TaskVisor',
'tasks.TaskWorkTypeModel',
'tasks.TaskWorkTypeTaskTypeModel',
'tasks.TmpSortedTableByPermission',
'tasks.TmpSortedTableByPermissionStep1',
'tasks.UserTaskSort',

'users.ProfileModel',
'users.CustomUser',

'workgroups.WorkgroupMemberOrganizationModel',
'workgroups.WorkgroupMemberOrganizationStatusModel',
'workgroups.WorkgroupMembersModel',
'workgroups.WorkgroupMembershipRole',
'workgroups.WorkgroupMembershipStatus',
'workgroups.WorkgroupModel',
'workgroups.WorkgroupStatus',
'workgroups.WorkgroupTypes',
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'request_line': {
            'format': '%(asctime)s [%(levelname)s] %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'request_line',
        },
    },
    'loggers': {
        # Логгер для твоего middleware
        'request_timing': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


try:
    from .local_settings import send_mikrot

except:
    def send_mikrot(client_ip):
        pass
