[program:aster_consumer]
command=python /app/asterisk_consumer.py
user=root
autostart=true
autorestart=true
stderr_logfile=/app/asterisk_consumer_err.log
stdout_logfile=/app/asterisk_consumer.log
directory=/app/
numprocs=1
startsecs=10
stopwaitsecs=30
killasgroup=true
