[program:bkz-django-q]
command = python /app/manage.py qcluster
user = root
autostart = true
autorestart = true
stdout_logfile = /app/django-q.log
redirect_stderr = true
directory = /app/
numprocs = 1
startsecs = 10
stopwaitsecs = 30
killasgroup = true
