[program:bot-delans]
command=python /app/welcome_bot.py
user=root
autostart=true
autorestart=true
stderr_logfile=/app/welcome_bot_err.log
stdout_logfile=/app/welcome_bot.log
directory=/app/
numprocs=1
startsecs=10
stopwaitsecs=30
killasgroup=true