[program:chat-handler-bkz3]
command=python /app/chat_handler.py
user=root
autostart=true
autorestart=true
stderr_logfile=/app/chat_handler_err.log
stdout_logfile=/app/chat_handler.log
directory=/app/
numprocs=1
startsecs=10
stopwaitsecs=30
killasgroup=true