[uwsgi]

chdir           = /app

module          = bkz3.wsgi:application

master          = true

processes       = 4

vacuum          = true
#touch-reload = /app/reload

#daemonize=/var/log/bkz/bkz_uwsgi.log
http = 0.0.0.0:5001
harakiri-verbose = True
enable-threads = True

# отключить стандартные строки лога запросов uWSGI
disable-logging = true

# (опционально) всё же логировать только ошибки 4xx/5xx силами uWSGI
log-4xx = true
log-5xx = true